### ISSUE TITLE
[Class] is not registered in this provider.

### ISSUE THREAD

**Issue by jasenf** [Cysharp/MemoryPack#119]
Hi,

I am trying to convert a fairly large project over to MemoryPack (we are excited to ditch Json :-)

I've marked up all our entities with [MemoryPackable], and even created a simple class to test, but I continue to get the 

**Classname not registered in this provider** exception.

My gut is that this has something to do with Roslyn code generation, but wouldn't know where to start to check if that is working or broken.  We aren't getting any error messages or warnings that I can see.  However, I can't hover over a class and see the MemoryPack items as the documentation suggests I should.

We are using VS2022 v17.4.4, are there any extensions that we need to install to get this to work?  

```
[MemoryPackable]
public partial class Results
{
        public int Count { get; set;}
        public string Test {get; set;}
}
var ir = new Results()
{
            Count = 1,
            Test = "this is a test"                        
};
var s = MemoryPackSerializer.Serialize<Results>(ir);
```

Any help or ideas what's wrong here would be appreciated!

**Comment by neuecc** [comment]
please check csproj, reference `MemoryPack`(not `MemoryPack.Core`).

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MemoryPack" Version="1.9.12" />
  </ItemGroup>

</Project>
```

it will generate code like this.

![image](https://user-images.githubusercontent.com/46207/217168427-e46ec4f6-6a70-4c6e-a742-01996d9c8947.png)

**Comment by jasenf** [comment]
Ok thank you, we eventually got it working.  We had to change the supported C# language version and some of those entries (OutputType), but it's working again, thank you.

Perhaps this should be more explicit in the documentation somewhere?  I looked again and am still missing it :-)

**Comment by neuecc** [comment]
Can you give an example of an exact, csproj that didn't work?

**Comment by YasiWonb** [comment]
> Can you give an example of an exact, csproj that didn't work? I have not yet grasped what you mean by conditions that do not work.

Hi neuecc,  I had the [same issue](https://stackoverflow.com/questions/75312853/memorypack-memorypackserializationexception-class-is-not-registered-in-this) 2 weeks ago and I can confirm than  replacing "MemoryPack.Core" with "MemoryPack" has solved it.

**Comment by neuecc** [comment]
Currently Visual Studio 2022 has bug of NuGet reference, first search result wil be secondaly one.
In other words, you may think you are searching for and referencing MemoryPack, but it may turn out to be MemoryPack.Core.
https://developercommunity.visualstudio.com/t/VS2022-Search-results-on-Nuget/10163787

**Comment by renatohgrimes** [comment]
Hi. I'm having a similar issue as this.

In my case, I have many other message objects like the following example, but it is throwing an exception:

My Program.cs:

```
using MemoryPack;

var msg = new CurrentValueMessage() { Millis = 111, Message = "hello world", Value = 123 };

var bytes = SerializeMessage(msg);

var result = MemoryPackSerializer.Deserialize(typeof(CurrentValueMessage), bytes);

Console.WriteLine("End.");

static byte[] SerializeMessage(IMessage message) => MemoryPackSerializer.Serialize(message);

internal partial interface IMessage { }

internal partial interface ISensorMessage : IMessage { } 

[MemoryPackable(SerializeLayout.Explicit)]
internal sealed partial class CurrentValueMessage : ISensorMessage
{
    [MemoryPackOrder(0)]
    public uint Millis { get; init; }

    [MemoryPackOrder(1)]
    public string? Message { get; init; }

    [MemoryPackOrder(2)]
    public byte Value { get; init; }
}
```

The exception:

```
Unhandled exception. MemoryPack.MemoryPackSerializationException: IMessage is not registered in this provider.
   at MemoryPack.MemoryPackSerializationException.ThrowNotRegisteredInProvider(Type type)
   at MemoryPack.ErrorMemoryPackFormatter`1.Throw()
   at MemoryPack.ErrorMemoryPackFormatter`1.Serialize[TBufferWriter](MemoryPackWriter`1& writer, T& value)
   at MemoryPack.MemoryPackSerializer.Serialize[T](T& value, MemoryPackSerializerOptions options)
   at Program.<<Main>$>g__SerializeMessage|0_0(IMessage message) in C:\Users\user\Demo\Program.cs:line 9
   at Program.<Main>$(String[] args) in C:\Users\user\Demo\Program.cs:line 5
```

My csproj file:

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MemoryPack" Version="1.9.13" />
  </ItemGroup>
</Project>
```

Am I implementing this correctly?

**Comment by YasiWonb** [comment]
Hi, maybe it's because class CurrentValueMessage is [MemoryPackable}, not interface  IMessage.

**Comment by AntoniSyty** [comment]
Hi. I use **MemoryPack**, not **MemoryPack.Core**, but ran into the same problem:

> MemoryPack.MemoryPackSerializationException: [Class] is not registered in this provider.
   at MemoryPack.MemoryPackSerializationException.ThrowNotRegisteredInProvider(Type type)
   at MemoryPack.ErrorMemoryPackFormatter`1.Throw()
   at MemoryPack.MemoryPackSerializer.Serialize[T](T& value, MemoryPackSerializeOptions options)

**Comment by invokemethod** [comment]
I'm experiencing the exact same issue as @AntoniSyty with the exact same version and TargetFramework.

**Comment by CeeSharpCore** [comment]
Hi Folks!

I face exactyl the same issue, however, I could verify, this only happens with a class defined in a different project of my solution. (I did take the right package "MemoryPack" without "core". But moving the class into the executing assembly circumvents this problem. All in all this is not a good solution as my solution is also quite large. >10 Projects.
...
my project settings (faulty one)

    <TargetFramework>net7.0</TargetFramework>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Nullable>enable</Nullable>
    <WarningsAsErrors>$(WarningsAsErrors);NU1605;CS8618;CS8603;CS8601;CS8604;CS8602</WarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="GitVersion.MsBuild" Version="5.12.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="MemoryPack" Version="1.9.13" />

.... etc.

**Comment by Sam6966** [comment]
Hi all,
I am also facing the same issue, my csproj file contains <PackageReference Include="MemoryPack" Version="1.9.13" />
but my bin folder contains MemoryPack.Core.dll.
Should this be MemoryPack.dll instead, as is suggested in the above messages?

**Comment by g3rzi** [comment]
I am facing the same issue, 
I installed MemoryPack from the [documentation](https://www.nuget.org/packages/MemoryPack):  
```
NuGet\Install-Package MemoryPack -Version 1.9.16
```

Also [Roslyn](https://www.nuget.org/packages/Microsoft.Net.Compilers/):
```
NuGet\Install-Package Microsoft.Net.Compilers -Version 4.2.0
```

I have Visual studio 2022 17.7.3, I am using the example from the documentation:  
```csharp
using MemoryPack;

namespace ConsoleApp1
{
    [MemoryPackable]
    public partial class Person
    {
        public int Age { get; set; }
        public string Name { get; set; }
    }

    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello, World!");
            var v = new Person { Age = 40, Name = "John" };
            var bin = MemoryPackSerializer.Serialize(v);
            var val = MemoryPackSerializer.Deserialize<Person>(bin);
            Console.WriteLine(val);
        }
    }
}
```

And I am getting the same error:  
```
Hello, World!
Unhandled exception. MemoryPack.MemoryPackSerializationException: ConsoleApp1.Person is not registered in this provider.
   at MemoryPack.MemoryPackSerializationException.ThrowNotRegisteredInProvider(Type type)
   at MemoryPack.ErrorMemoryPackFormatter`1.Throw()
   at MemoryPack.ErrorMemoryPackFormatter`1.Serialize[TBufferWriter](MemoryPackWriter`1& writer, T& value)
   at MemoryPack.MemoryPackSerializer.Serialize[T](T& value, MemoryPackSerializerOptions options)
   at ConsoleApp1.Program.Main(String[] args) in C:\Users\myuser\source\repos\MemoryPackConsole1\MemoryPackConsole1\Program.cs:line 27
```

My csproject file:  
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MemoryPack" Version="1.9.16" />
    <PackageReference Include="Microsoft.Net.Compilers" Version="4.2.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>

```


I still didn't understand what is the solution for that.
