### ISSUE TITLE
MemoryPack.MemoryPackSerializationException : Sequence reached end, reader can not provide more buffer.

### ISSUE THREAD

**Issue by tedbarth** [Cysharp/MemoryPack#204]
Version: 1.10.0 (also tested 1.9.x, 1.8.x and 1.7.x)
`$ dotnet --version` => 7.0.114 (bound to it because it will be used in newest Godot 4.2+)
`$ uname -a` => Linux myhostname 5.15.0-89-generic # 99-Ubuntu SMP Mon Oct 30 20:42:41 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

With the following test we get the error:
```
MemoryPack.MemoryPackSerializationException : Sequence reached end, reader can not provide more buffer.
   at MemoryPack.MemoryPackSerializationException.ThrowSequenceReachedEnd()
   at MemoryPack.MemoryPackReader.GetNextSpan(Int32 sizeHint)
   at memory_pack_bug_union.IntData.MemoryPack.IMemoryPackable<memory_pack_bug_union.IntData>.Deserialize(MemoryPackReader& reader, IntData& value) in /home/projects/memory-pack-bug-union/memory-pack-bug-union/MemoryPack.Generator/MemoryPack.Generator.MemoryPackGenerator/memory_pack_bug_union.IntData.MemoryPackFormatter.g.cs:line 98
   at memory_pack_bug_union.ISerializable.ISerializableFormatter.Deserialize(MemoryPackReader& reader, ISerializable& value) in /home/projects/memory-pack-bug-union/memory-pack-bug-union/MemoryPack.Generator/MemoryPack.Generator.MemoryPackGenerator/memory_pack_bug_union.ISerializable.MemoryPackFormatter.g.cs:line 119
   at MemoryPack.MemoryPackSerializer.Deserialize[T](ReadOnlySpan`1 buffer, T& value, MemoryPackSerializerOptions options)
   at MemoryPack.MemoryPackSerializer.Deserialize[T](ReadOnlySpan`1 buffer, MemoryPackSerializerOptions options)
   at memory_pack_bug_union.IntDataTest.SimulateTransfer[T](T serializable) in /home/projects/memory-pack-bug-union/memory-pack-bug-union/IntDataTest.cs:line 19
   at memory_pack_bug_union.IntDataTest.Test() in /home/projects/memory-pack-bug-union/memory-pack-bug-union/IntDataTest.cs:line 12
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

If I switch the **position** and **tag** of `typeof(BoolData)` and `typeof(IntData)` in `ISerializable` I instead get the following error (I assume this is a serialization, not a deserialization bug):
```
System.InvalidCastException : Unable to cast object of type 'memory_pack_bug_union.BoolData' to type 'memory_pack_bug_union.IntData'.
   at memory_pack_bug_union.IntDataTest.SimulateTransfer[T](T serializable) in /home/projects/memory-pack-bug-union/memory-pack-bug-union/IntDataTest.cs:line 20
   at memory_pack_bug_union.IntDataTest.Test() in /home/projects/memory-pack-bug-union/memory-pack-bug-union/IntDataTest.cs:line 12
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

We assume this is either a configuration or an environment problem, because this happens for older versions as well. In terms of configurational problems we can't spot the difference to other projects on github, example code in your documentation and issues with resolved problems. No idea what could be so specific.

I also tried without Nullable types and even renamed fields and classes.

----

The project:
```xml
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net7.0</TargetFramework>
        <RootNamespace>memory_pack_bug_union</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MemoryPack" Version="1.10.0" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.3.2" />
        <PackageReference Include="NUnit" Version="3.13.3" />
        <PackageReference Include="NUnit3TestAdapter" Version="4.2.1" />
        <PackageReference Include="NUnit.Analyzers" Version="3.3.0" />
        <PackageReference Include="coverlet.collector" Version="3.1.2" />
    </ItemGroup>

</Project>
```

Our classes (also attached as solution zip):
```c#
using MemoryPack;
using NUnit.Framework;

namespace memory_pack_bug_union;

public class IntDataTest {

  [Test]
  public void Test() {
    IntData data = new IntData(5);

    IntData transferred = SimulateTransfer(data);

    Assert.That(transferred, Is.EqualTo(data));
  }

  private static T SimulateTransfer<T>(T serializable) where T : ISerializable {
    var bytes = MemoryPackSerializer.Serialize(serializable);
    var deserialized = MemoryPackSerializer.Deserialize<ISerializable>(bytes)!;
    return (T) deserialized;
  }
}
```

```c#
using MemoryPack;

namespace memory_pack_bug_union;

[MemoryPackable]
[MemoryPackUnion(0, typeof(BoolData))]
[MemoryPackUnion(1, typeof(IntData))]
[MemoryPackUnion(2, typeof(DoubleData))]
public partial interface ISerializable {
}
```

Wrapper class which I will use in a bigger class as property behind `ISerializable` (Analog to `BoolData` and `DoubleData`):
```c#
using MemoryPack;

namespace memory_pack_bug_union;

[MemoryPackable]
public partial class IntData : ISerializable {
  public readonly int? Value;

  public IntData(int? value) {
    Value = value;
  }
}
```

The test project as solution:
[memory-pack-bug-union.zip](https://github.com/Cysharp/MemoryPack/files/13466326/memory-pack-bug-union.zip)

**Comment by tedbarth** [comment]
I found the issue. It is a usage error, of course.

I did:
`var bytes = MemoryPackSerializer.Serialize(serializable);`
Instead of:
`var bytes = MemoryPackSerializer.Serialize<ISerializable>(serializable);`

The documentation states this, though:
```
// Serialize as interface type.
var bin = MemoryPackSerializer.Serialize(data);
```

**Comment by hadashiA** [comment]
Thanks for the explanation.
This specification is a bit difficalt to change.

I would like to fix README. Thanks!
